all:
	pyuic5 main_menu.ui -o ../design/main_menu_design.py	
	pyuic5 create_menu.ui -o ../design/create_menu_design.py
	pyuic5 join_menu.ui -o ../design/join_menu_design.py
	pyuic5 game_screen.ui -o ../design/game_screen_design.py
