# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_menu.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_create_menu(object):
    def setupUi(self, create_menu):
        create_menu.setObjectName("create_menu")
        create_menu.resize(500, 600)
        self.centralwidget = QtWidgets.QWidget(create_menu)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 581))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.share_adr_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.share_adr_edit.setFont(font)
        self.share_adr_edit.setReadOnly(True)
        self.share_adr_edit.setObjectName("share_adr_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.share_adr_edit)
        self.verticalLayout.addLayout(self.formLayout)
        self.create_sever_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.create_sever_btn.setObjectName("create_sever_btn")
        self.verticalLayout.addWidget(self.create_sever_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.players_table = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.players_table.setTextElideMode(QtCore.Qt.ElideRight)
        self.players_table.setGridStyle(QtCore.Qt.SolidLine)
        self.players_table.setColumnCount(2)
        self.players_table.setObjectName("players_table")
        self.players_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.players_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.players_table.setHorizontalHeaderItem(1, item)
        self.players_table.horizontalHeader().setCascadingSectionResizes(False)
        self.players_table.horizontalHeader().setDefaultSectionSize(120)
        self.players_table.horizontalHeader().setHighlightSections(True)
        self.players_table.horizontalHeader().setMinimumSectionSize(90)
        self.players_table.horizontalHeader().setSortIndicatorShown(False)
        self.players_table.horizontalHeader().setStretchLastSection(True)
        self.players_table.verticalHeader().setVisible(True)
        self.players_table.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.players_table)
        self.start_game_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.start_game_btn.setFont(font)
        self.start_game_btn.setObjectName("start_game_btn")
        self.verticalLayout.addWidget(self.start_game_btn)
        self.back_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.back_btn.setObjectName("back_btn")
        self.verticalLayout.addWidget(self.back_btn)
        create_menu.setCentralWidget(self.centralwidget)

        self.retranslateUi(create_menu)
        QtCore.QMetaObject.connectSlotsByName(create_menu)

    def retranslateUi(self, create_menu):
        _translate = QtCore.QCoreApplication.translate
        create_menu.setWindowTitle(_translate("create_menu", "SuperDumass"))
        self.label.setText(_translate("create_menu", "Create Game"))
        self.label_4.setText(_translate("create_menu", "Address to share:"))
        self.create_sever_btn.setText(_translate("create_menu", "Create Server"))
        self.label_3.setText(_translate("create_menu", "List of players:"))
        item = self.players_table.horizontalHeaderItem(0)
        item.setText(_translate("create_menu", "Nickname"))
        item = self.players_table.horizontalHeaderItem(1)
        item.setText(_translate("create_menu", "IP"))
        self.start_game_btn.setText(_translate("create_menu", "Start game"))
        self.back_btn.setText(_translate("create_menu", "BACK"))
