# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'join_menu.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_join_menu(object):
    def setupUi(self, join_menu):
        join_menu.setObjectName("join_menu")
        join_menu.resize(500, 600)
        self.centralwidget = QtWidgets.QWidget(join_menu)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 581))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.adr_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.adr_edit.setFont(font)
        self.adr_edit.setText("")
        self.adr_edit.setReadOnly(False)
        self.adr_edit.setObjectName("adr_edit")
        self.gridLayout.addWidget(self.adr_edit, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.nickname_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.nickname_edit.setFont(font)
        self.nickname_edit.setText("")
        self.nickname_edit.setReadOnly(False)
        self.nickname_edit.setPlaceholderText("")
        self.nickname_edit.setObjectName("nickname_edit")
        self.gridLayout.addWidget(self.nickname_edit, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.wait_players_lable = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.wait_players_lable.setFont(font)
        self.wait_players_lable.setText("")
        self.wait_players_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.wait_players_lable.setObjectName("wait_players_lable")
        self.verticalLayout.addWidget(self.wait_players_lable)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.join_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.join_btn.sizePolicy().hasHeightForWidth())
        self.join_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.join_btn.setFont(font)
        self.join_btn.setObjectName("join_btn")
        self.verticalLayout.addWidget(self.join_btn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.back_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.back_btn.setFont(font)
        self.back_btn.setObjectName("back_btn")
        self.verticalLayout.addWidget(self.back_btn)
        join_menu.setCentralWidget(self.centralwidget)

        self.retranslateUi(join_menu)
        QtCore.QMetaObject.connectSlotsByName(join_menu)

    def retranslateUi(self, join_menu):
        _translate = QtCore.QCoreApplication.translate
        join_menu.setWindowTitle(_translate("join_menu", "SuperDumass"))
        self.label.setText(_translate("join_menu", "Join Game"))
        self.adr_edit.setPlaceholderText(_translate("join_menu", "0.0.0.0:8080"))
        self.label_2.setText(_translate("join_menu", "Enter the address"))
        self.label_3.setText(_translate("join_menu", "Your Nickname"))
        self.join_btn.setText(_translate("join_menu", "JOIN"))
        self.back_btn.setText(_translate("join_menu", "BACK"))
